### ISSUE TITLE
Remarks

### ISSUE THREAD

**Issue by pnpancholi** [jooohneth/SpeedRunEthereum-DEX#1]
1. The function "ethToToken" needs to return the tokenOutput.
2. The function "tokenToEth" needs to return the tokenOutput.
3. The function "deposit" needs to return tokenDeposit.
4. The function "withdraw" needs to return the amount of tokens withdrawn.

**Comment by zeroxjohn** [comment]
I believe, there is a misunderstanding, I do return those. If you meant the correct naming then I have changed it.
Thank you!
